Document endpoints.oauthRegistrationEndpoint for Actor objects
w3c-social/activitypump pull request #417
Opened 2024-01-12 22:03 UTC by ThisIsMissEm

Fixes #409, see there for more conversation.

2024-01-18 22:13 UTC, TallTed requested changes

2024-01-18 22:13 UTC, TallTed commented on index.html
> +            this endpoint specifies a URI at which a client may acquire an
```suggestion
            this endpoint specifies a URI at which a client may acquire a
```

2024-01-22 19:46 UTC, ThisIsMissEm commented
@TallTed have updated, sorry for the delay.

2024-03-04 16:56 UTC, TallTed approved these changes

2024-03-06 17:51 UTC, ThisIsMissEm commented
Closed as it's not a missing property, but rather, it's not actually mentioned in the spec.

2024-03-06 17:51 UTC, closed without merging